### ISSUE TITLE
Spoon solution for Live Contest

### ISSUE THREAD

**Issue by GerardPaligot** [TransformationToolContest/ttc15-live-contest-solutions#1]
I developed a solution for this live contest. For now, you can retrieve it on this [GitHub project](https://github.com/GerardPaligot/ttc15-live-contest).

If it is ok for you, I push my contribution on this project.

**Comment by tsdh** [comment]
Hi Gerard, wow, you are very fast. :-)

I've granted you push access, so you should now be able to push your solution to this repository.  Please add it in a `spoon` subdirectory and add a `README.md` illustrating how to run the solution.  Basically, it's fine if you only push the artifacts needed to run the solution (i.e., a runnable JAR or so), and link to the actual solution project from the `README.md`.

And of course, feel free to update your solution as often as you want until the deadline on Thursday noon.

**Comment by tsdh** [comment]
Ah, I accidentally closed the issue so I reopened it.  Please close it yourself after having pushed your solution and it really worked.

**Comment by GerardPaligot** [comment]
Ok, so I must develop a main class to launch my solution. For now, there is only a simply test case. I develop that and I push the project.

**Comment by tsdh** [comment]
Great, thanks. And congrats for submitting the very first solution.

**Comment by GerardPaligot** [comment]
Thanks. 

I don't know why but I got an error 403 when I try to push on this project. So I create a PR (#2).
