### ISSUE TITLE
Epsilon Pattern Language Solution for Live Contest

### ISSUE THREAD

**Issue by kolovos** [TransformationToolContest/ttc15-live-contest-solutions#3]

**Comment by kolovos** [comment]
The EPL solution is available under https://dl.dropboxusercontent.com/u/5636547/org.eclipse.epsilon.examples.epl.j2j.zip

The executable shell script and JAR (j2j.sh/jar) are located under the dist/ directory of the zip archive

**Comment by arcanefoam** [comment]
We have update our solution, having some issues getting the jar available, we will post it in a few mins

**Comment by arcanefoam** [comment]
The link to the jar: https://drive.google.com/a/york.ac.uk/file/d/0B6fcNvaeWCsKYmVrOEF4cXd4Q2M/view?usp=sharing
The -h is an actual option, the print is a bit misleading.
The application receives two arguments: "path/to/src" and "path/to/gen" and injects the classes in the src and saves them in the gen folder.

The source files are available here:
https://github.com/kb634/ttc2015-live

**Comment by tsdh** [comment]
@arcanefoam I've invited you to join the Participants team so that you get push access to this repository.  Please push the jar to some `epsilon` subdirectory, and add a `README.md` mentioning how to run it and linking your solution project.  Thanks!

**Comment by arcanefoam** [comment]
Done. Thanks!

**Comment by arcanefoam** [comment]
Not yet. I don't have access to the repository :( for push

**Comment by tsdh** [comment]
In the github administration interface, it is shown that you haven't accepted the invitation yet.  You should have received some email where you have to click some confirmation link.
